# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', sorl.thumbnail.fields.ImageField(upload_to='flatpage/%Y/%m/%d')),
                ('url', models.CharField(blank=True, max_length=150)),
                ('flatpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flatpages.FlatPage')),
            ],
        ),
        migrations.CreateModel(
            name='FlatPageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('keywords', models.CharField(blank=True, help_text='Separate keywords by commas', max_length=250)),
                ('description', models.TextField(blank=True, verbose_name='meta description')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='flatpages.FlatPage')),
            ],
            options={
                'verbose_name_plural': 'Page MetaData',
                'verbose_name': 'Page MetaData',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('content_source', models.TextField()),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('view_count', models.IntegerField(default=0, editable=False)),
                ('flatpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='flatpages.FlatPage')),
            ],
        ),
    ]
